### ISSUE TITLE
Contributing to SciPy?

### ISSUE THREAD

**Issue by fpedd** [yymao/TracyWidom#1]
Have you thought about contributing your code to SciPy? It would be really cool to have the Tracy-Widom distribution in `scipy.stats` :)

**Comment by yymao** [comment]
Thanks for the suggestion. I'm not sure about the standards, if any, for `scipy.stats` to include a distribution, but I'll look into it.

**Comment by fpedd** [comment]
Somewhat offtopic: I would like to use this as part of my bachelor thesis on spectrum sensing for cognitive radio: 1. Is that okay with you (I guess it is, MIT license)? 2. Do you have any preference on citing your work? If you add smth. to your readme I will use that, else I will come up with something on my own. :)

Btw: The first [link](https://www.cl.cam.ac.uk/~aib29/TWinSplus.pdf) in your readme gives a 403, no premission.

**Comment by yymao** [comment]
@fabianpedd Unfortunately the PDF file disappeared from their server, but I found the original references. I've added them to the README. 

You are very welcome to use this package in your work! It is MIT licensed so there's really no requirement to use it. But you can consider citing the original papers and listing URL to this repo (i.e., `https://github.com/yymao/TracyWidom`). I've added this to the README too.

**Comment by fpedd** [comment]
Great, thank you very much for all your work! :+1:
